#ifndef STEAM_AUDIO_PROBE_VOLUME_H
#define STEAM_AUDIO_PROBE_VOLUME_H

#include "godot_cpp/classes/node3d.hpp"
#include "godot_cpp/classes/wrapped.hpp"
#include "godot_cpp/variant/packed_vector3_array.hpp"
#include "phonon.h"
#include <atomic>

using namespace godot;

// Generates probes across a box volume, bakes a single reverb reflections layer into them
// (source and listener both at probe position, interpolated at runtime from the listener's
// nearest probes), and saves/loads the result to disk so baking only has to happen once.
// bake() is synchronous/blocking - there's no async baking pipeline yet (Phase 2 MVP scope);
// expect it to freeze the editor for the duration of the bake.
class SteamAudioProbeVolume : public Node3D {
	GDCLASS(SteamAudioProbeVolume, Node3D);

private:
	IPLProbeBatch batch = nullptr;
	std::atomic<bool> registered;
	// Positions captured at generation time, straight from IPLProbeArray - IPLProbeBatch (what
	// actually persists after baking/loading) has no position-query API in this SDK, so this is
	// the only way to inspect placement after the fact. Only populated by bake(); empty after a
	// disk load, since the saved format doesn't carry positions back out either.
	PackedVector3Array probe_positions;

	void ready_internal();
	void register_probes();
	void unregister_probes();
	String resolve_data_path() const;

protected:
	static void _bind_methods();

public:
	Vector3 size = Vector3(10.f, 10.f, 10.f);
	float probe_spacing = 5.0f;
	float probe_height = 1.5f;
	int num_rays = 4096;
	int num_bounces = 16;
	float simulated_duration = 2.0f;
	float saved_duration = 1.0f;
	int ambisonics_order = 1;
	String probe_data_path;

	SteamAudioProbeVolume();
	~SteamAudioProbeVolume();
	void _notification(int p_what);

	// Generates probes across the volume, bakes reflections data into them, and saves the
	// result to probe_data_path (or a default next to the scene file, if empty). Returns
	// whether the bake succeeded. Editor/tool-callable; also safe to call at runtime.
	bool bake();
	int get_num_probes() const;
	// World-space positions of the probes generated by the most recent bake() call in this
	// session. Empty if nothing has been baked yet (or if data was only loaded from disk) -
	// see the probe_positions field comment.
	PackedVector3Array get_probe_positions() const { return probe_positions; }

	Vector3 get_size() const { return size; }
	void set_size(Vector3 p_size) { size = p_size; }
	float get_probe_spacing() const { return probe_spacing; }
	void set_probe_spacing(float p_probe_spacing) { probe_spacing = p_probe_spacing; }
	float get_probe_height() const { return probe_height; }
	void set_probe_height(float p_probe_height) { probe_height = p_probe_height; }
	int get_num_rays() const { return num_rays; }
	void set_num_rays(int p_num_rays) { num_rays = p_num_rays; }
	int get_num_bounces() const { return num_bounces; }
	void set_num_bounces(int p_num_bounces) { num_bounces = p_num_bounces; }
	float get_simulated_duration() const { return simulated_duration; }
	void set_simulated_duration(float p_simulated_duration) { simulated_duration = p_simulated_duration; }
	float get_saved_duration() const { return saved_duration; }
	void set_saved_duration(float p_saved_duration) { saved_duration = p_saved_duration; }
	int get_ambisonics_order() const { return ambisonics_order; }
	void set_ambisonics_order(int p_ambisonics_order) { ambisonics_order = p_ambisonics_order; }
	String get_probe_data_path() const { return probe_data_path; }
	void set_probe_data_path(String p_probe_data_path) { probe_data_path = p_probe_data_path; }

	PackedStringArray _get_configuration_warnings() const override;
};

#endif // STEAM_AUDIO_PROBE_VOLUME_H
